name: "代码测试与检查"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: 设置 Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    
    - name: 安装依赖
      run: npm install
    
    - name: 运行测试
      run: npm test
      
    - name: 生成测试覆盖率报告
      run: npm run test:coverage 